### ISSUE TITLE
Chapter 3 - "Hypothesis Testing: t-test for comparing two samples mean"

### ISSUE THREAD

**Issue by ThunderRod** [Lazuardis/DESinPython#1]
Hi Lazuardis, thank you a lot for your valuable contribution through Medium articles/tutorials related  "Discrete Event Simulation using Python SimPy"

Related Chapter 3, can you provide the file "observed_data.csv" in the GitHub repository that you use in the .ipynb file? thank you in advance:

# Load the observation data

observed_data = pd.read_csv('observed_data.csv').to_numpy().flatten()

Best regards,

**Comment by Lazuardis** [comment]
Hi there, thanks for the interest.

I have uploaded the file on the Github folder. However, just bear in mind that if you use that csv file, the hypothesis testing result may appear different from the Colab file I've provided. There is this one thing I found from _SimPy_ library (or from the _random_ library package) is that the random seed would only keep the result the same within one kernel run. So if you restart the kernel session, it will generate different set of random numbers, thus the hypothesting testing result will differ as now the generated simulation result data has changed. 

I suggest if you want to experiment with particularly the hypothesis testing part, you could synthesize the _observed_data_ that suit your needs or suit your simulation result using [numpy.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html)

**Comment by ThunderRod** [comment]
Hi Lazuardis, thanks for the file!

Related to the random seed, I agree. A solution that works for me is the following:

You can place the command "random.seed(100)" just below the lines of code where you import the libraries.

                  # import the corresponding libraries

                  import simpy
                  import pandas as pd
                  import numpy as np
                  import random
                  import matplotlib.pyplot as plt
                  import seaborn as sns
                  
                  random.seed(100) #random seed to preserve same random number generated

This allows you to get the same random numbers every time you run the code.

Thanks again, regards!

**Comment by Lazuardis** [comment]
Hi ThunderRod,

That's sublime, never thought that could be done.
Thanks for the tips!, regards
